<?php

$labels = array();
$labels['vacation'] = 'Autoodpowiedź';
$labels['vacationenable'] = 'Włączona';
$labels['vacationsubject'] = 'Temat';
$labels['vacationmessage'] = 'Treść';
$labels['vacationforwarder'] = 'Forward address';
$labels['vacationstart'] = 'Od kiedy';
$labels['vacationend'] = 'Do kiedy';

$labels['period'] = 'Okres';
$labels['frequency'] = 'Częstotliwość';
$labels['addressed_to'] = 'Adresowana do';
$labels['append_subject'] = 'Dołącz temat';
$labels['send_from'] = 'Wyślij z';
$labels['vacationfrom'] = 'Od';
$labels['vacationto'] = 'Do';
$labels['answer_no_more_than_every'] = 'Odpowiedz nie częściej niż co';
$labels['vacationdays'] = 'dzień';
$labels['wholeday'] = 'Cały dzień';

$messages = array();
$messages['vacationinvalidstartdate'] = 'Proszę wybrać prawidłową datę początkową.';
$messages['vacationinvalidenddate'] = 'Proszę wybrać prawidłową datę zakończenia.';
$messages['vacationinvaliddateinterval'] = 'Przedział czasu jest nieprawidłowy.';
$messages['vacationnosubject'] = 'Proszę wpisać temat autoodpowiedzi.';
$messages['vacationnomessage'] = 'Proszę wpisać treść autoodpowiedzi.';
$messages['vacationinvalidforwarder'] = 'Adres przekierowania nie jest prawidłowy.';
$messages['vacationinvalidforwarders'] = 'Lista adresów przekierowań nie jest prawidłowa.';
$messages['vacationdriverdefaulterror'] = 'Nieznany błąd';
$messages['vacationdriverconnecterror'] = 'Błąd podczas połączenia';
$messages['vacationdriverprocesserror'] = 'Błąd przetwarzania danych';
